/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ds.h"
#include <sys/vfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <unistd.h>


void
dsprog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	getattr_res result_1;
	getattr_req  getattr_1_arg;
	enum clnt_stat retval_2;
	readdir_res result_2;
	readdir_req  readdir_1_arg;
	enum clnt_stat retval_3;
	mkdir_res result_3;
	mkdir_req  mkdir_1_arg;
	enum clnt_stat retval_4;
	unlink_res result_4;
	unlink_req  unlink_1_arg;
	enum clnt_stat retval_5;
	rmdir_res result_5;
	rmdir_req  rmdir_1_arg;
	enum clnt_stat retval_6;
	rename_res result_6;
	rename_req  rename_1_arg;
	enum clnt_stat retval_7;
	mknod_res result_7;
	mknod_req  mknod_1_arg;
	enum clnt_stat retval_8;
	create_res result_8;
	create_req  create_1_arg;
	enum clnt_stat retval_9;
	open_res result_9;
	open_req  open_1_arg;
	enum clnt_stat retval_10;
	close_res result_10;
	close_res  close_1_arg;
	enum clnt_stat retval_11;
	read_res result_11;
	read_req  read_1_arg;
	enum clnt_stat retval_12;
	write_res result_12;
	write_req  write_1_arg;
	enum clnt_stat retval_13;
	lookup_res result_13;
	lookup_req  lookup_1_arg;
	enum clnt_stat retval_14;
	truncate_res result_14;
	truncate_req  truncate_1_arg;
	enum clnt_stat retval_15;
	statfs_res result_15;
	statfs_req  statfs_1_arg;
	enum clnt_stat retval_16;
	chmod_res result_16;
	chmod_req  chmod_1_arg;
	enum clnt_stat retval_17;
	chown_res result_17;
	chown_req  chown_1_arg;
	enum clnt_stat retval_18;
	link_res result_18;
	link_req  link_1_arg;
	enum clnt_stat retval_19;
	symlink_res result_19;
	symlink_req  symlink_1_arg;
	enum clnt_stat retval_20;
	readlink_res result_20;
	readlink_req  readlink_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DSPROG, DSVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = getattr_1(&getattr_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = readdir_1(&readdir_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = mkdir_1(&mkdir_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = unlink_1(&unlink_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = rmdir_1(&rmdir_1_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = rename_1(&rename_1_arg, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = mknod_1(&mknod_1_arg, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_8 = create_1(&create_1_arg, &result_8, clnt);
	if (retval_8 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_9 = open_1(&open_1_arg, &result_9, clnt);
	if (retval_9 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_10 = close_1(&close_1_arg, &result_10, clnt);
	if (retval_10 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_11 = read_1(&read_1_arg, &result_11, clnt);
	if (retval_11 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_12 = write_1(&write_1_arg, &result_12, clnt);
	if (retval_12 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_13 = lookup_1(&lookup_1_arg, &result_13, clnt);
	if (retval_13 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_14 = truncate_1(&truncate_1_arg, &result_14, clnt);
	if (retval_14 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_15 = statfs_1(&statfs_1_arg, &result_15, clnt);
	if (retval_15 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_16 = chmod_1(&chmod_1_arg, &result_16, clnt);
	if (retval_16 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_17 = chown_1(&chown_1_arg, &result_17, clnt);
	if (retval_17 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_18 = link_1(&link_1_arg, &result_18, clnt);
	if (retval_18 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_19 = symlink_1(&symlink_1_arg, &result_19, clnt);
	if (retval_19 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_20 = readlink_1(&readlink_1_arg, &result_20, clnt);
	if (retval_20 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dsprog_1 (host);
exit (0);
}
