/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mds.h"
#include <sys/vfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <unistd.h>

/*
 * READ : argp->op == READ request.
 *  - This is a read request so, we open the corresponding file and then
 *      - search for the argp->offset in the list of records.
 *        copy the matching records into the result
 *
 * WRITE :
 *  - Here we check if the record exists (just like for READ). If found return
 *  the entry.
 *  - If not found create a new record for the give length and return it.
 */ 
bool_t
getlayout_1_svc(getlayout_req *argp, getlayout_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * NOT needed. 
 */
bool_t
access_1_svc(access_req *argp, access_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server
 */
bool_t
create_1_svc(create_req *argp, create_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * NOT needed.
 */
bool_t
search_1_svc(query_req *argp, query_rec *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

int
mdprog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}

/*
 * Same as ds_server.
 * Here we might have to read the contents of the first line of the file for the
 * size value.
 */
bool_t
getattr_mds_1_svc(getattr_req *argp, getattr_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
readdir_mds_1_svc(readdir_req *argp, readdir_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
mkdir_mds_1_svc(mkdir_req *argp, mkdir_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * We will need to parse the contents of the file to find all the ds_servers
 * that have the stripes of this file and unlink them.
 */
bool_t
unlink_mds_1_svc(unlink_req *argp, unlink_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * We will need to parse the contents of the file to find all the ds_servers
 * that have the stripes of this file and unlink them.
 */
bool_t
rmdir_mds_1_svc(rmdir_req *argp, rmdir_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * We will need to parse the contents of the file to find all the ds_servers
 * that have the stripes of this file and rename them.
 */
bool_t
rename_mds_1_svc(rename_req *argp, rename_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
mknod_mds_1_svc(mknod_req *argp, mknod_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
create_mds_1_svc(create_req *argp, create_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
open_mds_1_svc(open_req *argp, open_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
close_mds_1_svc(close_req *argp, close_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * This should NOT be called on MDS. So, we can eliminate this.
 */
bool_t
read_mds_1_svc(read_req *argp, read_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * This should NOT be called on MDS. So, we can eliminate this.
 */
bool_t
write_mds_1_svc(write_req *argp, write_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server
 */
bool_t
lookup_mds_1_svc(lookup_req *argp, lookup_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * This is a little complicated.
 * - If we are reducing the size :
 *      - Walk through all the ds_server entries and unlink those stripes which
 *      fall out of the range.
 *      - Truncate the partial length if any.
 *      - Update the size.
 * - For the size is extended
 *      - Update the size.
 */
bool_t
truncate_mds_1_svc(truncate_req *argp, truncate_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
statfs_mds_1_svc(statfs_req *argp, statfs_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
chmod_mds_1_svc(chmod_req *argp, chmod_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
chown_mds_1_svc(chown_req *argp, chown_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 */
bool_t
link_mds_1_svc(link_req *argp, link_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 * NEEDS SOME THOUGHT
 */
bool_t
symlink_mds_1_svc(symlink_req *argp, symlink_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

/*
 * Same as ds_server.
 * NEEDS SOME THOUGHT
 */
bool_t
readlink_mds_1_svc(readlink_req *argp, readlink_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
mount_mds_1_svc(mount_req *argp, mount_res *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	return retval;
}

