/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ind.h"

bool_t
xdr_registry_rec (XDR *xdrs, registry_rec *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->peer, MAXNAME))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fname, MAXNAME))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bw))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_req (XDR *xdrs, query_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->fname, MAXNAME))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_rec (XDR *xdrs, query_rec *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->count))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( MAXCOUNT ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->bw, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->bw;
					i < MAXCOUNT; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->count))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( MAXCOUNT ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->bw, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->bw;
					i < MAXCOUNT; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->bw, MAXCOUNT,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
