/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

bool_t
xdr_rd_wr_t(xdrs, objp)
	register XDR *xdrs;
	rd_wr_t *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	int i;
	if (!xdr_opaque(xdrs, objp->file, 1024))
		return (FALSE);
	if (!xdr_opaque(xdrs, objp->buf, 1024))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->offset))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->size))
		return (FALSE);
	return (TRUE);
}
