/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define	_NFS_H_RPCGEN

#include <rpc/rpc.h>

struct rd_wr_t {
	char file[1024];
	char buf[1024];
	int offset;
	int size;
};
typedef struct rd_wr_t rd_wr_t;

#define	OURNFS	0x20000002
#define	OURNFSVERS	1
#define	READ	1
extern  int * read_1();
#define	WRITE	2
extern  int * write_1();
extern int ournfs_1_freeresult();

/* the xdr functions */
extern bool_t xdr_rd_wr_t();

#endif /* !_NFS_H_RPCGEN */
