/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "mds_ds.h"
#include "mds_ds_misc.h"
#include <sys/vfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <unistd.h>

int getattr_c(char *ds_svr, char *path, struct stat *buf)
{
    getattr_req req;
    getattr_res res;
    CLIENT *clnt;
    bool_t ret;

#ifdef DEBUG
    printf("getattr_c(ds_svr=%s, path=%s, sbuf)\n", ds_svr, path);
#endif
    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;

    ret = getattr_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    } else
        errno = 0;

    // individually copy the items
    buf->st_dev = res.sbuf.stat_dev;
    buf->st_ino = res.sbuf.stat_ino;
    buf->st_mode = res.sbuf.stat_mode;
    buf->st_nlink = res.sbuf.stat_nlink; 
    buf->st_uid = res.sbuf.stat_uid; 
    buf->st_gid = res.sbuf.stat_gid;
    buf->st_rdev = res.sbuf.stat_rdev; 
    buf->st_size = res.sbuf.stat_size;
    buf->st_blksize = res.sbuf.stat_blksize;
    buf->st_blocks =  res.sbuf.stat_blocks;
    buf->st_atime = res.sbuf.stat_atime;
    buf->st_mtime = res.sbuf.stat_mtime;
    buf->st_ctime = res.sbuf.stat_ctime;

    clnt_destroy(clnt);
    return res.res;
}

int readdir_c(char *ds_svr, char *path, off_t offset, struct dirent *dentry)
{
    readdir_req req;
    readdir_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.d_off = offset;

    ret = readdir_ds_1(&req,&res,clnt);

#ifdef DEBUG
    printf("readdir_c: Returned from readdir_ds_1()\n");
#endif
    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

#ifdef DEBUG
    /*
    printf("readdir_c : d_name=%s d_ino=%ul d_off=%l d_reclen=%d d_type=%d\n",
            res.dent.d_name, res.dent.d_ino, res.dent.d_off, res.dent.d_reclen, res.dent.d_type);
            */
#endif
    // individually copy the items
    printf(" Here 0\n");
    dentry->d_ino = (int) res.dent.d_ino;
    dentry->d_ino = 0;
    printf(" Here 1\n");
    dentry->d_off = (int) res.dent.d_off;
    printf(" Here 2\n");
    dentry->d_reclen = res.dent.d_reclen;
    printf(" Here 3\n");
    dentry->d_type = res.dent.d_type;
    printf(" Here 4\n");
    strcpy(dentry->d_name, res.dent.d_name);
    printf(" Here 5\n");

    clnt_destroy(clnt);
    return res.res;
}

int mkdir_c(char *ds_svr, char *path, mode_t mode)
{
    mkdir_req req;
    mkdir_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.mode = mode;

    ret = mkdir_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int unlink_c(char *ds_svr, char *path)
{
    unlink_req req;
    unlink_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;

    ret = unlink_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}


int rmdir_c(char *ds_svr, char *path)
{
    rmdir_req req;
    rmdir_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;

    ret = rmdir_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int rename_c(char *ds_svr, char *oldpath, char *newpath)
{
    rename_req req;
    rename_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.old = oldpath;
    req.new = newpath;

    ret = rename_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int mknod_c(char *ds_svr, char *path, mode_t mode, dev_t dev)
{
    mknod_req req;
    mknod_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.mode = mode;
    req.dev = dev;

    ret = mknod_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int create_c(char *ds_svr, char *path, mode_t mode)
{
    create_req req;
    create_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.mode = mode;

    ret = create_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int open_c(char *ds_svr, char *path, int flags, mode_t mode)
{
    open_req req;
    open_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.flags = flags;
    req.mode = mode;

    ret = open_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int close_c(char *ds_svr, char *path)
{
    close_req req;
    close_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;

    ret = close_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int read_c(char *ds_svr, char *path, off_t offset, size_t size, char *buf)
{
    read_req req;
    read_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.offset = offset;
    req.count = size;
#ifdef DEBUG
    printf("read_c: path=%s offset=%lu res.count=%lu size=%lu\n", path,
            (unsigned long)req.offset, (unsigned long)req.count, (unsigned long)size);
#endif
    ret = read_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
        return (-EIO);
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    // individually copy the items
    //
    memcpy(buf, res.data, res.res);
#ifdef DEBUG
    printf("read_c: res.res=%d res.data=%s\n", res.res, res.data);
#endif
    clnt_destroy(clnt);
    return res.res;
}

int write_c(char *ds_svr, char *path, off_t offset, size_t count, char *buf)
{
    write_req req;
    write_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    memcpy(req.data, buf, count); 
    req.offset = offset;
    req.count = count;

    ret = write_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int lookup_c(char *ds_svr, char *path)
{
    lookup_req req;
    lookup_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;

    ret = lookup_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int truncate_c(char *ds_svr, char *path, off_t length)
{
    truncate_req req;
    truncate_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.len = length;

    ret = truncate_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int statfs_c(char *ds_svr, char *path, struct my_statfs *buf)
{
    statfs_req req;
    statfs_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;

    ret = statfs_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    // individually copy the items
    //
    buf->f_type = res.stat.f_type;
    buf->f_bsize = res.stat.f_bsize;
    buf->f_blocks = res.stat.f_blocks;
    buf->f_bfree = res.stat.f_bfree;
    buf->f_bavail = res.stat.f_bavail;
    buf->f_files = res.stat.f_files;
    buf->f_ffree = res.stat.f_ffree;
    buf->f_fsid.__val[0] = res.stat.f_fsid.__val[0];
    buf->f_fsid.__val[1] = res.stat.f_fsid.__val[1];
    buf->f_namelen = res.stat.f_namelen;

    clnt_destroy(clnt);
    return res.res;
}

int chmod_c(char *ds_svr, char *path, mode_t mode)
{
    chmod_req req;
    chmod_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.mode = mode;

    ret = chmod_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int chown_c(char *ds_svr, char *path, uid_t uid, gid_t gid)
{
    chown_req req;
    chown_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.uid = uid;
    req.gid = gid;

    ret = chown_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int link_c(char *ds_svr, char *old, char *new)
{
    link_req req;
    link_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.old = old;
    req.new = new;

    ret = link_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int symlink_c(char *ds_svr, char *old, char * new)
{
    symlink_req req;
    symlink_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.old = old;
    req.new = new;

    ret = symlink_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    clnt_destroy(clnt);
    return res.res;
}

int readlink_c(char *ds_svr, char *path, char *buf, size_t bufsize)
{
    readlink_req req;
    readlink_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(ds_svr, DSPROG, DSVERS, "tcp")) == NULL) {
        clnt_pcreateerror(ds_svr);
        return(res.res);
    }

    req.name = path;
    req.bufsize = bufsize;

    ret = readlink_ds_1(&req,&res,clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
    }

    if (res.res  < 0) {
        errno = -(res.res);
        return (res.res);
    }

    /*
     * Copy the result back to the buffer.
     */
    strcpy(buf, res.buf);

    clnt_destroy(clnt);
    return res.res;
}

int getlayout_c(char *mds_svr, char *fname, off_t off, size_t len, int op, size_t *sz, layout_rec *rec)
{
    getlayout_req req;
    getlayout_res res;
    CLIENT *clnt;
    bool_t ret;

    if ((clnt = clnt_create(mds_svr, MDPROG, MDVERS, "tcp")) == NULL) {
        clnt_pcreateerror(mds_svr);
        return(-EIO);
    }

    req.fname = fname;
    req.offset = off;
    req.len = len;
    req.op = op;

    ret = getlayout_1(&req, &res, clnt);

    if (ret != RPC_SUCCESS) {
        printf("ret = %d\n",ret);
        clnt_perror(clnt, "call failed");
        return (-EIO);
    }

    /*
     * TODO :
     * For now we just copy the first extent as that is the one which maps into
     * the range that was asked for.
     *
     * As an optimization we could make pnfs_read() query the entire range that
     * it needs instead of STRIPE_SZ.
     */
    if (res.cnt) {
        rec->off = res.recs[0].off;
        rec->len = res.recs[0].len;
        strcpy(rec->dsname, res.recs[0].dsname);
        strcpy(rec->extname, res.recs[0].extname);
        *sz = res.sz;
    }
    return (0);
}

