/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ds.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include <sys/vfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <unistd.h>

static void
dsprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		getattr_req getattr_1_arg;
		readdir_req readdir_1_arg;
		mkdir_req mkdir_1_arg;
		unlink_req unlink_1_arg;
		rmdir_req rmdir_1_arg;
		rename_req rename_1_arg;
		mknod_req mknod_1_arg;
		create_req create_1_arg;
		open_req open_1_arg;
		close_res close_1_arg;
		read_req read_1_arg;
		write_req write_1_arg;
		lookup_req lookup_1_arg;
		truncate_req truncate_1_arg;
		statfs_req statfs_1_arg;
		chmod_req chmod_1_arg;
		chown_req chown_1_arg;
		link_req link_1_arg;
		symlink_req symlink_1_arg;
		readlink_req readlink_1_arg;
	} argument;
	union {
		getattr_res getattr_1_res;
		readdir_res readdir_1_res;
		mkdir_res mkdir_1_res;
		unlink_res unlink_1_res;
		rmdir_res rmdir_1_res;
		rename_res rename_1_res;
		mknod_res mknod_1_res;
		create_res create_1_res;
		open_res open_1_res;
		close_res close_1_res;
		read_res read_1_res;
		write_res write_1_res;
		lookup_res lookup_1_res;
		truncate_res truncate_1_res;
		statfs_res statfs_1_res;
		chmod_res chmod_1_res;
		chown_res chown_1_res;
		link_res link_1_res;
		symlink_res symlink_1_res;
		readlink_res readlink_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case getattr:
		_xdr_argument = (xdrproc_t) xdr_getattr_req;
		_xdr_result = (xdrproc_t) xdr_getattr_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))getattr_1_svc;
		break;

	case readdir:
		_xdr_argument = (xdrproc_t) xdr_readdir_req;
		_xdr_result = (xdrproc_t) xdr_readdir_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))readdir_1_svc;
		break;

	case mkdir:
		_xdr_argument = (xdrproc_t) xdr_mkdir_req;
		_xdr_result = (xdrproc_t) xdr_mkdir_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))mkdir_1_svc;
		break;

	case unlink:
		_xdr_argument = (xdrproc_t) xdr_unlink_req;
		_xdr_result = (xdrproc_t) xdr_unlink_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))unlink_1_svc;
		break;

	case rmdir:
		_xdr_argument = (xdrproc_t) xdr_rmdir_req;
		_xdr_result = (xdrproc_t) xdr_rmdir_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))rmdir_1_svc;
		break;

	case rename:
		_xdr_argument = (xdrproc_t) xdr_rename_req;
		_xdr_result = (xdrproc_t) xdr_rename_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))rename_1_svc;
		break;

	case mknod:
		_xdr_argument = (xdrproc_t) xdr_mknod_req;
		_xdr_result = (xdrproc_t) xdr_mknod_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))mknod_1_svc;
		break;

	case create:
		_xdr_argument = (xdrproc_t) xdr_create_req;
		_xdr_result = (xdrproc_t) xdr_create_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))create_1_svc;
		break;

	case open:
		_xdr_argument = (xdrproc_t) xdr_open_req;
		_xdr_result = (xdrproc_t) xdr_open_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))open_1_svc;
		break;

	case close:
		_xdr_argument = (xdrproc_t) xdr_close_res;
		_xdr_result = (xdrproc_t) xdr_close_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))close_1_svc;
		break;

	case read:
		_xdr_argument = (xdrproc_t) xdr_read_req;
		_xdr_result = (xdrproc_t) xdr_read_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))read_1_svc;
		break;

	case write:
		_xdr_argument = (xdrproc_t) xdr_write_req;
		_xdr_result = (xdrproc_t) xdr_write_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))write_1_svc;
		break;

	case lookup:
		_xdr_argument = (xdrproc_t) xdr_lookup_req;
		_xdr_result = (xdrproc_t) xdr_lookup_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))lookup_1_svc;
		break;

	case truncate:
		_xdr_argument = (xdrproc_t) xdr_truncate_req;
		_xdr_result = (xdrproc_t) xdr_truncate_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))truncate_1_svc;
		break;

	case statfs:
		_xdr_argument = (xdrproc_t) xdr_statfs_req;
		_xdr_result = (xdrproc_t) xdr_statfs_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))statfs_1_svc;
		break;

	case chmod:
		_xdr_argument = (xdrproc_t) xdr_chmod_req;
		_xdr_result = (xdrproc_t) xdr_chmod_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))chmod_1_svc;
		break;

	case chown:
		_xdr_argument = (xdrproc_t) xdr_chown_req;
		_xdr_result = (xdrproc_t) xdr_chown_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))chown_1_svc;
		break;

	case link:
		_xdr_argument = (xdrproc_t) xdr_link_req;
		_xdr_result = (xdrproc_t) xdr_link_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))link_1_svc;
		break;

	case symlink:
		_xdr_argument = (xdrproc_t) xdr_symlink_req;
		_xdr_result = (xdrproc_t) xdr_symlink_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))symlink_1_svc;
		break;

	case readlink:
		_xdr_argument = (xdrproc_t) xdr_readlink_req;
		_xdr_result = (xdrproc_t) xdr_readlink_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))readlink_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!dsprog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (DSPROG, DSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DSPROG, DSVERS, dsprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DSPROG, DSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DSPROG, DSVERS, dsprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DSPROG, DSVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
