/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "mds.h"
#include <sys/vfs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <unistd.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
getattr_mds_1(getattr_req *argp, getattr_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, getattr_mds,
		(xdrproc_t) xdr_getattr_req, (caddr_t) argp,
		(xdrproc_t) xdr_getattr_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
readdir_mds_1(readdir_req *argp, readdir_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, readdir_mds,
		(xdrproc_t) xdr_readdir_req, (caddr_t) argp,
		(xdrproc_t) xdr_readdir_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mkdir_mds_1(mkdir_req *argp, mkdir_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, mkdir_mds,
		(xdrproc_t) xdr_mkdir_req, (caddr_t) argp,
		(xdrproc_t) xdr_mkdir_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unlink_mds_1(unlink_req *argp, unlink_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, unlink_mds,
		(xdrproc_t) xdr_unlink_req, (caddr_t) argp,
		(xdrproc_t) xdr_unlink_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rmdir_mds_1(rmdir_req *argp, rmdir_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, rmdir_mds,
		(xdrproc_t) xdr_rmdir_req, (caddr_t) argp,
		(xdrproc_t) xdr_rmdir_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
rename_mds_1(rename_req *argp, rename_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, rename_mds,
		(xdrproc_t) xdr_rename_req, (caddr_t) argp,
		(xdrproc_t) xdr_rename_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mknod_mds_1(mknod_req *argp, mknod_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, mknod_mds,
		(xdrproc_t) xdr_mknod_req, (caddr_t) argp,
		(xdrproc_t) xdr_mknod_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
create_mds_1(create_req *argp, create_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, create_mds,
		(xdrproc_t) xdr_create_req, (caddr_t) argp,
		(xdrproc_t) xdr_create_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
open_mds_1(open_req *argp, open_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, open_mds,
		(xdrproc_t) xdr_open_req, (caddr_t) argp,
		(xdrproc_t) xdr_open_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
close_mds_1(close_req *argp, close_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, close_mds,
		(xdrproc_t) xdr_close_req, (caddr_t) argp,
		(xdrproc_t) xdr_close_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
read_mds_1(read_req *argp, read_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, read_mds,
		(xdrproc_t) xdr_read_req, (caddr_t) argp,
		(xdrproc_t) xdr_read_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
write_mds_1(write_req *argp, write_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, write_mds,
		(xdrproc_t) xdr_write_req, (caddr_t) argp,
		(xdrproc_t) xdr_write_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
lookup_mds_1(lookup_req *argp, lookup_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, lookup_mds,
		(xdrproc_t) xdr_lookup_req, (caddr_t) argp,
		(xdrproc_t) xdr_lookup_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
truncate_mds_1(truncate_req *argp, truncate_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, truncate_mds,
		(xdrproc_t) xdr_truncate_req, (caddr_t) argp,
		(xdrproc_t) xdr_truncate_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
statfs_mds_1(statfs_req *argp, statfs_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, statfs_mds,
		(xdrproc_t) xdr_statfs_req, (caddr_t) argp,
		(xdrproc_t) xdr_statfs_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
chmod_mds_1(chmod_req *argp, chmod_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, chmod_mds,
		(xdrproc_t) xdr_chmod_req, (caddr_t) argp,
		(xdrproc_t) xdr_chmod_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
chown_mds_1(chown_req *argp, chown_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, chown_mds,
		(xdrproc_t) xdr_chown_req, (caddr_t) argp,
		(xdrproc_t) xdr_chown_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
link_mds_1(link_req *argp, link_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, link_mds,
		(xdrproc_t) xdr_link_req, (caddr_t) argp,
		(xdrproc_t) xdr_link_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
symlink_mds_1(symlink_req *argp, symlink_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, symlink_mds,
		(xdrproc_t) xdr_symlink_req, (caddr_t) argp,
		(xdrproc_t) xdr_symlink_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
readlink_mds_1(readlink_req *argp, readlink_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, readlink_mds,
		(xdrproc_t) xdr_readlink_req, (caddr_t) argp,
		(xdrproc_t) xdr_readlink_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
mount_mds_1(mount_req *argp, mount_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, mount_mds,
		(xdrproc_t) xdr_mount_req, (caddr_t) argp,
		(xdrproc_t) xdr_mount_res, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getlayout_1(getlayout_req *argp, getlayout_res *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, getlayout,
		(xdrproc_t) xdr_getlayout_req, (caddr_t) argp,
		(xdrproc_t) xdr_getlayout_res, (caddr_t) clnt_res,
		TIMEOUT));
}
