/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ind.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

typedef union argument {
		registry_rec registry_1_arg;
		query_req search_1_arg;
} argument_t;

typedef union result {
		int registry_1_res;
		query_rec search_1_res;
} result_t;


/*
 * Struct to encapsulate the args to the threaded service routine.
 */
typedef struct tdata {
    struct svc_req  *rqstp;
    SVCXPRT         *transp;
	bool_t (*local)(char *, void *, struct svc_req *);
    argument_t      argument;
    result_t        result; 
    xdrproc_t       _xdr_argument;
    xdrproc_t       _xdr_result;
} tdata_t;

/*
 * Modified service routine. This is the routine executed by the service threads
 * spawned by the dispatcher routine.
 * Logic outline :
 * - It extracts the args from the void poineter passed to it.
 * - It called the necessary server method and replies to the client with the
 *   results.
 */
void *
service_request(void *data )
{
    tdata_t *tdata_p;
	argument_t *argument;
	result_t *result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);
    struct svc_req *rqstp;
    register SVCXPRT *transp;

#ifdef DEBUG
    printf("service_request() : Entered\n");
#endif

    /*
     * Extract the args from the argument passed.
     */
    tdata_p = (tdata_t *) data;
    rqstp = tdata_p->rqstp;
    transp = tdata_p->transp;
    local = tdata_p->local;
    argument = &(tdata_p->argument);
    result = &(tdata_p->result);
    _xdr_result = tdata_p->_xdr_result;

#ifdef DEBUG
    printf("rq_proc = %d\n", (int)rqstp->rq_proc);
    printf("Calling the service routine\n");
#endif

	retval = (bool_t) (*local)((char *)argument, (void *)result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)result)) {
		svcerr_systemerr (transp);
	}

#ifdef DEBUG
    printf("Completed the service routine\n");
#endif

    /*
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}

	if (!indsrvprog_1_freeresult (transp, _xdr_result, (caddr_t) result))
		fprintf (stderr, "%s", "unable to free results");
    */

    /*
     * Free the data buffer which was allocated by the dispatcher.
     */
    free(data);
	return;
}

pthread_t threadp;
pthread_attr_t attr;

/*
 * Modified dispatch routine. Outline of the code :
 * - This routine is called by svc_run() when a new rpc request arrives.
 * - This routine spawns a new thread for every incoming and hands it (request)
 *   out to that thread to service it.
 */
static void
indsrvprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
    tdata_t *datap = (tdata_t *)malloc(sizeof (tdata_t));

    /*
     * If we fail to allocate memory we quit.
     */
    if (datap == NULL) {
        printf("Failed to allocate memory for the request args !\n");
        exit(1);
    }
   
    datap->rqstp = rqstp;
    datap->transp = transp;

    switch (rqstp->rq_proc) {
    case NULLPROC:
        (void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
        return;

    case registry:
        datap->_xdr_argument = (xdrproc_t) xdr_registry_rec;
        datap->_xdr_result = (xdrproc_t) xdr_int;
        datap->local = (bool_t (*) (char *, void *,  struct svc_req *))registry_1_svc;
        break;

    case search:
        datap->_xdr_argument = (xdrproc_t) xdr_query_req;
        datap->_xdr_result = (xdrproc_t) xdr_query_rec;
        datap->local = (bool_t (*) (char *, void *,  struct svc_req *))search_1_svc;
        break;

    default:
        svcerr_noproc (transp);
        return;
    }
    memset ((char *)&(datap->argument), 0, sizeof (datap->argument));
    if (!svc_getargs (transp, (xdrproc_t) datap->_xdr_argument, (caddr_t) &(datap->argument))) {
        svcerr_decode (transp);
        return;
    }
 
    /*
     * We want the service threads to be reaped automatically.
     */
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);

    /*
     * Spawn a new thread and pass it the rpc request for it to process it.
     */
#ifdef DEBUG
    printf("Spawning a new thread\n");
#endif
    pthread_create(&threadp, &attr, service_request, (void *)datap);
#ifdef DEBUG
    printf("Spawned a new thread\n");
#endif
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (INDSRVPROG, INDSRVVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, INDSRVPROG, INDSRVVERS, indsrvprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (INDSRVPROG, INDSRVVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, INDSRVPROG, INDSRVVERS, indsrvprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (INDSRVPROG, INDSRVVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
