/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "obtain.h"

bool_t
xdr_my_time_t (XDR *xdrs, my_time_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAME))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seek_bytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filedata (XDR *xdrs, filedata objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datareceived (XDR *xdrs, datareceived *objp)
{
	register int32_t *buf;

	 if (!xdr_filedata (xdrs, objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readfile_res (XDR *xdrs, readfile_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	switch (objp->error) {
	case 0:
		 if (!xdr_datareceived (xdrs, &objp->readfile_res_u.chunk))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_file_rec (XDR *xdrs, file_rec *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->hostname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pflag))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ver))
		 return FALSE;
	 if (!xdr_my_time_t (xdrs, &objp->ttr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_req (XDR *xdrs, query_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->fname, MAXNAME))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_rec (XDR *xdrs, query_rec *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->count))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( MAXCOUNT  + MAXCOUNT ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->pflags, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->vers, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->pflags;
				i < MAXCOUNT; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		{
			register int *genp;

			for (i = 0, genp = objp->vers;
				i < MAXCOUNT; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->ttrs, MAXCOUNT,
			sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->mtime, MAXCOUNT,
			sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->eof))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->count))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( MAXCOUNT  + MAXCOUNT ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->pflags, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->vers, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->pflags;
				i < MAXCOUNT; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		{
			register int *genp;

			for (i = 0, genp = objp->vers;
				i < MAXCOUNT; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->ttrs, MAXCOUNT,
			sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->mtime, MAXCOUNT,
			sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->eof))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pflags, MAXCOUNT,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->vers, MAXCOUNT,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ttrs, MAXCOUNT,
		sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mtime, MAXCOUNT,
		sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->eof))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_msg_id (XDR *xdrs, msg_id *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->hostid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seqno))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b_query_req (XDR *xdrs, b_query_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uphost, MAXHOSTNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b_hitquery_reply (XDR *xdrs, b_hitquery_reply *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_msg_id (xdrs, &objp->id))
			 return FALSE;
         printf("xdr_b_hitquery_reply: msg_id done\n");
		 if (!xdr_int (xdrs, &objp->cnt))
			 return FALSE;
         printf("xdr_b_hitquery_reply: cnt done\n");
		 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
         printf("xdr_b_hitquery_reply: fname done\n");
		 if (!xdr_vector (xdrs, (char *)objp->hosts, BUFSIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
         printf("xdr_b_hitquery_reply: hosts done\n");
		buf = XDR_INLINE (xdrs, ( MAXCOUNT  + MAXCOUNT ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->pflags, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
         printf("xdr_b_hitquery_reply: pflags done\n");
			 if (!xdr_vector (xdrs, (char *)objp->vers, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
         printf("xdr_b_hitquery_reply: vers done\n");

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->pflags;
				i < MAXCOUNT; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		{
			register int *genp;

			for (i = 0, genp = objp->vers;
				i < MAXCOUNT; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->ttrs, MAXCOUNT,
			sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
			 return FALSE;
         printf("xdr_b_hitquery_reply: ttrs done\n");
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_msg_id (xdrs, &objp->id))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->cnt))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->hosts, BUFSIZE,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( MAXCOUNT  + MAXCOUNT ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->pflags, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->vers, MAXCOUNT,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		{
			register int *genp;

			for (i = 0, genp = objp->pflags;
				i < MAXCOUNT; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		{
			register int *genp;

			for (i = 0, genp = objp->vers;
				i < MAXCOUNT; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_vector (xdrs, (char *)objp->ttrs, MAXCOUNT,
			sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cnt))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hosts, BUFSIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pflags, MAXCOUNT,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->vers, MAXCOUNT,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ttrs, MAXCOUNT,
		sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_invalidate_req (XDR *xdrs, invalidate_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->originsvr, MAXHOSTNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ver))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_invalidate_res (XDR *xdrs, invalidate_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_req (XDR *xdrs, update_req *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->fname))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_res (XDR *xdrs, update_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_addcache_req (XDR *xdrs, addcache_req *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->fname))
		 return FALSE;
	 if (!xdr_filename (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ver))
		 return FALSE;
	 if (!xdr_my_time_t (xdrs, &objp->ttr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_addcache_res (XDR *xdrs, addcache_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_req (XDR *xdrs, validate_req *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->fname))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ver))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_res (XDR *xdrs, validate_res *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXPATHLEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_file_rec (xdrs, &objp->frec))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
