/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "obtain.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
obtainprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		request obtain_1_arg;
		query_req search_1_arg;
		addcache_req addcache_1_arg;
		b_query_req b_query_1_arg;
		b_hitquery_reply b_hitquery_1_arg;
		invalidate_req invalidate_1_arg;
		update_req update_1_arg;
		validate_req validate_1_arg;
	} argument;
	union {
		readfile_res obtain_1_res;
		query_rec search_1_res;
		addcache_res addcache_1_res;
		update_res update_1_res;
		validate_res validate_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case obtain:
		_xdr_argument = (xdrproc_t) xdr_request;
		_xdr_result = (xdrproc_t) xdr_readfile_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))obtain_1_svc;
		break;

	case search:
		_xdr_argument = (xdrproc_t) xdr_query_req;
		_xdr_result = (xdrproc_t) xdr_query_rec;
		local = (bool_t (*) (char *, void *,  struct svc_req *))search_1_svc;
		break;

	case addcache:
		_xdr_argument = (xdrproc_t) xdr_addcache_req;
		_xdr_result = (xdrproc_t) xdr_addcache_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))addcache_1_svc;
		break;

	case b_query:
		_xdr_argument = (xdrproc_t) xdr_b_query_req;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))b_query_1_svc;
		break;

	case b_hitquery:
		_xdr_argument = (xdrproc_t) xdr_b_hitquery_reply;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))b_hitquery_1_svc;
		break;

	case invalidate:
		_xdr_argument = (xdrproc_t) xdr_invalidate_req;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))invalidate_1_svc;
		break;

	case update:
		_xdr_argument = (xdrproc_t) xdr_update_req;
		_xdr_result = (xdrproc_t) xdr_update_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))update_1_svc;
		break;

	case validate:
		_xdr_argument = (xdrproc_t) xdr_validate_req;
		_xdr_result = (xdrproc_t) xdr_validate_res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))validate_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!obtainprog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OBTAINPROG, OBTAINVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OBTAINPROG, OBTAINVER, obtainprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OBTAINPROG, OBTAINVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OBTAINPROG, OBTAINVER, obtainprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OBTAINPROG, OBTAINVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
