/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "obtain.h"

bool_t
xdr_my_time_t (XDR *xdrs, my_time_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAME))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seek_bytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filedata (XDR *xdrs, filedata objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datareceived (XDR *xdrs, datareceived *objp)
{
	register int32_t *buf;

	 if (!xdr_filedata (xdrs, objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readfile_res (XDR *xdrs, readfile_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	switch (objp->error) {
	case 0:
		 if (!xdr_datareceived (xdrs, &objp->readfile_res_u.chunk))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_file_rec (XDR *xdrs, file_rec *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->hostname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pflag))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rev))
		 return FALSE;
	 if (!xdr_my_time_t (xdrs, &objp->ttr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_req (XDR *xdrs, query_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->fname, MAXNAME))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_rec (XDR *xdrs, query_rec *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->recs, MAXCOUNT,
		sizeof (file_rec), (xdrproc_t) xdr_file_rec))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mtime, MAXCOUNT,
		sizeof (my_time_t), (xdrproc_t) xdr_my_time_t))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->eof))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_msg_id (XDR *xdrs, msg_id *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->hostid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seqno))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b_query_req (XDR *xdrs, b_query_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uphost, MAXHOSTNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b_hitquery_reply (XDR *xdrs, b_hitquery_reply *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cnt))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->recs, MAXCOUNT,
		sizeof (file_rec), (xdrproc_t) xdr_file_rec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_invalidate_req (XDR *xdrs, invalidate_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->originsvr, MAXHOSTNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ver))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_req (XDR *xdrs, update_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_update_res (XDR *xdrs, update_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
