#!/bin/ksh

BASEDIR="~/cs550/pa2/"
ssh compute-0-0 "pkill obtain_server"
ssh compute-0-1 "pkill obtain_server"
ssh compute-0-2 "pkill obtain_server"
ssh compute-0-3 "pkill obtain_server"
ssh compute-0-5 "pkill obtain_server"
ssh compute-0-6 "pkill obtain_server"
ssh compute-0-7 "pkill obtain_server"
ssh compute-0-8 "pkill obtain_server"
ssh compute-0-9 "pkill obtain_server"
ssh compute-0-10 "pkill obtain_server"
ssh compute-0-11 "pkill obtain_server"
ssh compute-0-12 "pkill obtain_server"
