/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "obtain.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAME))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seek_bytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filedata (XDR *xdrs, filedata objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datareceived (XDR *xdrs, datareceived *objp)
{
	register int32_t *buf;

	 if (!xdr_filedata (xdrs, objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readfile_res (XDR *xdrs, readfile_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_datareceived (xdrs, &objp->readfile_res_u.chunk))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_query_req (XDR *xdrs, query_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->fname, MAXNAME))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_rec (XDR *xdrs, query_rec *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->peers, BUFSIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->eof))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_msg_id (XDR *xdrs, msg_id *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->hostid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seqno))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b_query_req (XDR *xdrs, b_query_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ttl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uphost, MAXHOSTNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b_hitquery_reply (XDR *xdrs, b_hitquery_reply *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_msg_id (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cnt))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fname, MAXNAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hosts, BUFSIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
