/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "obtain.h"


void
obtainprog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	readfile_res result_1;
	request  obtain_1_arg;
	enum clnt_stat retval_2;
	query_rec result_2;
	query_req  search_1_arg;
	enum clnt_stat retval_3;
	int result_3;
	b_query_req  b_query_1_arg;
	enum clnt_stat retval_4;
	int result_4;
	b_hitquery_reply  b_hitquery_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, OBTAINPROG, OBTAINVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = obtain_1(&obtain_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = search_1(&search_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = b_query_1(&b_query_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = b_hitquery_1(&b_hitquery_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	obtainprog_1 (host);
exit (0);
}
