/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ind.h"

bool_t
xdr_registry_rec (XDR *xdrs, registry_rec *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->peer, MAXNAME))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fname, MAXNAME))
		 return FALSE;
	return TRUE;
}
